language: python

python:
  - 3.5

install:
  - pip install -r requirements.txt

script:
  - flake8 cmdbox
  - python get_cur_version.py
  - python -m unittest tests.py
  - python -m unittest mock_tests.py	
